# Generated by Django 4.2.7 on 2023-11-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idClient', models.IntegerField()),
                ('clientName', models.CharField(max_length=50)),
                ('clientAddress', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('discount', models.FloatField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='clientPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clientinfo')),
            ],
        ),
    ]
