# Generated by Django 4.2.7 on 2023-11-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="historyCorp",
            fields=[
                (
                    "clientinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Clients.clientinfo",
                    ),
                ),
                ("RUT", models.IntegerField()),
                ("discount", models.FloatField()),
            ],
            bases=("Clients.clientinfo",),
        ),
        migrations.CreateModel(
            name="historyPerson",
            fields=[
                (
                    "clientinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Clients.clientinfo",
                    ),
                ),
                ("DNI", models.IntegerField()),
            ],
            bases=("Clients.clientinfo",),
        ),
        migrations.RemoveField(
            model_name="clientinfo",
            name="idClient",
        ),
        migrations.RemoveField(
            model_name="corporation",
            name="idClient",
        ),
        migrations.RemoveField(
            model_name="person",
            name="idClient",
        ),
        migrations.AddField(
            model_name="corporation",
            name="clientinfo_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="Clients.clientinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="clientinfo_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="Clients.clientinfo",
            ),
            preserve_default=False,
        ),
    ]
