# Generated by Django 4.2.7 on 2023-11-11 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Clients", "0002_remove_corporation_idclient_remove_person_idclient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientinfo",
            name="idClient",
        )
    ]
