# Generated by Django 4.2.7 on 2023-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_remove_corporation_idclient_remove_person_idclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyCorp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=75)),
                ('RUT', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='historyPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=75)),
                ('DNI', models.IntegerField()),
            ],
        ),
    ]
