# Generated by Django 4.2.7 on 2023-11-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_historycorp_historyperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historycorp',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historycorp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historyperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historyperson',
            name='id',
        ),
        migrations.AddField(
            model_name='historycorp',
            name='clientinfo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Clients.clientinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyperson',
            name='clientinfo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Clients.clientinfo'),
            preserve_default=False,
        ),
    ]
