# Generated by Django 4.2.7 on 2023-11-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_users',
        ),
    ]
