# Generated by Django 4.2.7 on 2023-11-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBranch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='dirección',
            new_name='address',
        ),
    ]
