# Generated by Django 4.2.7 on 2023-11-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("StoreBranch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productBranchId",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="StoreBranch.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="branch",
            name="branchId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="productId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
