# Generated by Django 4.2.7 on 2023-11-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBranch', '0002_delete_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Stock',
        ),
    ]
