# Generated by Django 4.2.7 on 2023-11-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBranch', '0003_rename_product_stock'),
    ]

    operations = [
       
    ]
