# Generated by Django 4.2.7 on 2023-11-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBranch', '0004_branchhistory_producthistory'),
    ]

    operations = [
       
       
    ]
