# Generated by Django 4.2.7 on 2023-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreBranch", "0005_rename_product_stock_and_more"),
    ]

    operations = [

        migrations.CreateModel(
            name="branchHistory",
            fields=[
                ("branchId", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="productHistory",
            fields=[
                ("productId", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                ("category", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
    ]
